server:
    port: 8080

spring:
    application:
        name: payment-service-app
    datasource: # ?????????? ? ???? ????????? ??????????? ? ??
        url: jdbc:postgresql://localhost:5432/payment-db # URL ??????????? ? ??
        username: admin # ??? ????????????
        password: secret # ??????
        driver-class-name: org.postgresql.Driver # ????? jdbc ????????
    jpa:
        hibernate:
            ddl-auto: validate
            show-sql: true # ?????????? SQL-??????? ? ???????
        properties:
            hibernate:
                format_sql: true # ????????????? SQL ??? ??????????
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    liquibase:
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.yaml
