name: Build Project for PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Шаг 3: Компиляция проекта
      - name: Compile with Maven
        run: mvn -B clean compile

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: mvn -B test

      # Шаг 5: Checkstyle
      - name: Run checkstyle for payment-service-application
        working-directory: ./payment-service-application
        run: mvn -B checkstyle:check
